export const API_ERROR_INVALID_CREDENTIALS = `INVALID_CREDENTIALS`;
export const API_ERROR_USER_ALREADY_ACTIVATED = `USER_ALREADY_ACTIVATED`;
export const API_ERROR_USER_INACTIVE = `USER_INACTIVE`;
export const API_ERROR_USER_NOT_FOUND = `USER_NOT_FOUND`;
export const API_ERROR_USER_EMAIL_IN_USE = `USER_EMAIL_IN_USE`;
export const API_ERROR_UNHANDLED = `UNHANDLED`;
