export const ONBOARDING_SCREEN = `ONBOARDING_SCREEN`;
export const COUNTRY_SELECTION_SCREEN = `COUNTRY_SELECTION_SCREEN`;
export const EHIC_SELECTION_SCREEN = `EHIC_SELECTION_SCREEN`;
export const OCCUPATION_SELECTION_SCREEN = `OCCUPATION_SELECTION_SCREEN`;
export const UNIVERSITY_SELECTION_SCREEN = `UNIVERSITY_SELECTION_SCREEN`;
export const DIGIME_SCREEN = `DIGIME_SCREEN`;
export const LOADING_AND_RESULT_SCREEN = `LOADING_AND_RESULT_SCREEN`;

export const WALLET_SCREEN = 'Insurances';
export const TRAVEL_SCREEN = 'Travel';
export const ASSISTANCE_SCREEN = 'Assistance';

export const TRAVEL_DESTINATION_SELECTION = 'TRAVEL_DESTINATION_SELECTION';
export const TRAVEL_ACTIVITY_SELECTION = 'TRAVEL_ACTIVITY_SELECTION';
export const TRAVEL_RESULTS = 'TRAVEL_RESULTS';

export const GET_STARTED_SCREEN = 'GET_STARTED_SCREEN';

