export const hospitals = [
    {
        "ID": 60611,
        "Extension": 1,
        "Name": "Terveystalo Ruoholahti Hospital",
        "PostalAddress": "Porkkalankatu 22 C",
        "ZIP": "00180",
        "Post Office": "Helsinki",
        "Phone number": "0417172753",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60611,
        "Organization": "Terveystalo Ruoholahti Sairaala",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1639851,
        "Longitude": 24.9087927,
        "Covered Upfront": 0,
        "Genral": 1,
        "Dental": 0,
        "Bone": 1,
        "Vision": 0
    },
    {
        "ID": 60626,
        "Extension": 1,
        "Name": "Hospital Mehiläinen Helsinki",
        "PostalAddress": "Pohjoinen Hesperiankatu 17",
        "ZIP": "00260",
        "Post Office": "Helsinki",
        "Phone number": "0341728927",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60626,
        "Organization": "Mehiläinen Oyj (Helsinki)",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1773557,
        "Longitude": 24.9235208,
        "Covered Upfront": 1,
        "Genral": 0,
        "Dental": 0,
        "Bone": 0,
        "Vision": 1
    },
    {
        "ID": 60694,
        "Extension": 1,
        "Name": "Dextra Hospital",
        "PostalAddress": "Annankatu 11 B 11",
        "ZIP": "00120",
        "Post Office": "Helsinki",
        "Phone number": "0456172873",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60694,
        "Organization": "Dextra Oy Plastiikkakirurginen Sairaala",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1675557,
        "Longitude": 24.9359583,
        "Covered Upfront": 0,
        "Genral": 1,
        "Dental": 1,
        "Bone": 1,
        "Vision": 1
    },
    {
        "ID": 60702,
        "Extension": 1,
        "Name": "Suomen Terveystalo Helsinki",
        "PostalAddress": "Jaakonkatu 3",
        "ZIP": "00100",
        "Post Office": "Helsinki",
        "Phone number": "0672376837",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60702,
        "Organization": "Suomen Terveystalo Oyj/Helsinki",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1696944,
        "Longitude": 24.932085,
        "Covered Upfront": 0,
        "Genral": 0,
        "Dental": 1,
        "Bone": 0,
        "Vision": 0
    },
    {
        "ID": 60738,
        "Extension": 2,
        "Name": "Bulevard Clinic",
        "PostalAddress": "Bulevardi 22",
        "ZIP": "00120",
        "Post Office": "Helsinki",
        "Phone number": "0467287292",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60738,
        "Organization": "Bulevardin Klinikka Oy",
        "the service sector accounts": "171,250,261,262,263",
        "Service Sector": "Private hospital (esh),Työterveyshuolto,Yleislääk. vastaanotto,Specialist's cabinet,Kirurgiset toimenpiteet",
        "Latitude": 60.164278,
        "Longitude": 24.9473298,
        "Covered Upfront": 0,
        "Genral": 1,
        "Dental": 0,
        "Bone": 0,
        "Vision": 0
    },
    {
        "ID": 60776,
        "Extension": 2,
        "Name": "Helsinki General Hospital Ltd",
        "PostalAddress": "Länsisatamankatu 16",
        "ZIP": "00180",
        "Post Office": "Helsinki",
        "Phone number": "0426282372",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60776,
        "Organization": "Tays Sydänkeskus Oy",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1594033,
        "Longitude": 24.9096849,
        "Covered Upfront": 1,
        "Genral": 0,
        "Dental": 0,
        "Bone": 1,
        "Vision": 1
    },
    {
        "ID": 60785,
        "Extension": 1,
        "Name": "Apollo Hospital",
        "PostalAddress": "Uudenmaankatu 38",
        "ZIP": "00120",
        "Post Office": "Helsinki",
        "Phone number": "0637623762",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60785,
        "Organization": "Plastiikkakirurginen sairaala KL Oy",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.1629556,
        "Longitude": 24.936791,
        "Covered Upfront": 1,
        "Genral": 0,
        "Dental": 1,
        "Bone": 1,
        "Vision": 1
    },
    {
        "ID": 60843,
        "Extension": 1,
        "Name": "Docrates Eye Hospital",
        "PostalAddress": "Saukonpaadenranta 2",
        "ZIP": "00180",
        "Post Office": "Helsinki",
        "Phone number": "0237623872",
        "Munciplatity Code": 91,
        "Munciplaity": "Helsinki",
        "Language": "fi",
        "organizational ID": 60843,
        "Organization": "Docrates Oy",
        "the service sector accounts": 171,
        "Service Sector": "Private hospital (esh)",
        "Latitude": 60.160451,
        "Longitude": 24.919904,
        "Covered Upfront": 0,
        "Genral": 0,
        "Dental": 0,
        "Bone": 0,
        "Vision": 1
    }
];
